### ISSUE TITLE
DuckDB-less Splink

### ISSUE THREAD

**Issue by ThomasHepworth** [moj-analytical-services/splink#1242]
Hello,

For reasons that are confidential, my organization is not able to install duckdb on AWS EMR and we still need to run Splink using pySpark.

For the most part everything works fine, except the function;
linker.estimate_u_using_random_sampling(target_rows=5e5)

It yields the error;

Traceback (most recent call last):
  File "/efs/dq_i/python/aws3-011123/aws3/lib/python3.10/site-packages/splink/linker.py", line 879, in estimate_u_using_random_sampling
    estimate_u_values(self, target_rows)
  File "/efs/dq_i/python/aws3-011123/aws3/lib/python3.10/site-packages/splink/estimate_u.py", line 138, in estimate_u_values
    param_records = compute_proportions_for_new_parameters(param_records)
  File "/efs/dq_i/python/aws3-011123/aws3/lib/python3.10/site-packages/splink/expectation_maximisation.py", line 90, in compute_proportions_for_new_parameters
    return duckdb.query(sql).to_df().to_dict("records")

I am wondering if there is a work around for this? Does duckdb HAVE to be installed for the estimate_u_using_random_sampling function to work?

_Originally posted by @JoeGanser in https://github.com/moj-analytical-services/splink/discussions/1239_

**Comment by RossKen** [comment]
@ThomasHepworth I assume this is good to be closed now?
