### ISSUE TITLE
linker aborted  Failed to execute user defined function($anonfun$261: (string, string) =&gt; double)

### ISSUE THREAD

**Issue by Freewilly3d** [moj-analytical-services/splink#182]
I have expanded my dataset and am now running into this error. 
typeguard 2.11.1
splink 1.04

Py4JJavaError                             Traceback (most recent call last)
<command-439717876983944> in <module>
      2 #linker = Splink(settings, spark, df_l=df_l, df_r=df_r)
      3 linker = Splink(settings, [df_l, df_r], spark)
----> 4 df_e = linker.get_scored_comparisons()
      5 
      6 # Later, we will make term frequency adjustments.

/databricks/python/lib/python3.7/site-packages/splink/__init__.py in get_scored_comparisons(self, compute_ll)
     97             self.spark,
     98             compute_ll=compute_ll,
---> 99             save_state_fn=self.save_state_fn,
    100         )
    101 

/databricks/python/lib/python3.7/site-packages/typeguard/__init__.py in wrapper(*args, **kwargs)
    910         memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
    911         check_argument_types(memo)
--> 912         retval = func(*args, **kwargs)
    913         try:
    914             check_return_type(retval, memo)

/databricks/python/lib/python3.7/site-packages/splink/iterate.py in iterate(df_gammas, model, spark, compute_ll, save_state_fn)
     41         df_e = run_expectation_step(df_gammas, model, spark, compute_ll=compute_ll)
     42 
---> 43         run_maximisation_step(df_e, model, spark)
     44 
     45         logger.info(f"Iteration {i} complete")

/databricks/python/lib/python3.7/site-packages/splink/maximisation_step.py in run_maximisation_step(df_e, model, spark)
    110     df_intermediate.persist()
    111 
--> 112     new_lambda = _get_new_lambda(df_intermediate, spark)
    113     pi_df_collected = _get_new_pi_df(df_intermediate, spark, model)
    114 

/databricks/python/lib/python3.7/site-packages/splink/maximisation_step.py in _get_new_lambda(df_intermediate, spark)
     30     sql = _sql_gen_new_lambda(table_name="df_intermediate")
     31 
---> 32     new_lambda = spark.sql(sql).collect()[0][0]
     33     logger.debug(_format_sql(sql))
     34     return new_lambda

/databricks/spark/python/pyspark/sql/dataframe.py in collect(self)
    552         # Default path used in OSS Spark / for non-DF-ACL clusters:
    553         with SCCallSiteSync(self._sc) as css:
--> 554             sock_info = self._jdf.collectToPython()
    555         return list(_load_from_socket(sock_info, BatchedSerializer(PickleSerializer())))
    556 

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o8969.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 11 in stage 1147.0 failed 4 times, most recent failure: Lost task 11.3 in stage 1147.0 (TID 54760, 10.255.128.8, executor 14): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$261: (string, string) => double)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$15$$anon$2.hasNext(WholeStageCodegenExec.scala:659)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1235)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:366)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:364)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1252)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:537)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:543)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid text
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at org.apache.commons.text.similarity.RegexTokenizer.tokenize(RegexTokenizer.java:43)
	at org.apache.commons.text.similarity.RegexTokenizer.tokenize(RegexTokenizer.java:34)
	at org.apache.commons.text.similarity.CosineDistance.apply(CosineDistance.java:49)
	at uk.gov.moj.dash.linkage.CosineDistance.call(Similarity.scala:218)
	at uk.gov.moj.dash.linkage.CosineDistance.call(Similarity.scala:214)
	at org.apache.spark.sql.UDFRegistration$$anonfun$261.apply(UDFRegistration.scala:777)
	... 53 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2362)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2350)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2349)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2349)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2582)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2529)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2517)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:897)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2282)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2380)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:245)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:280)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:80)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:86)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:508)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:480)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:330)
	at org.apache.spark.sql.Dataset$$anonfun$50.apply(Dataset.scala:3358)
	at org.apache.spark.sql.Dataset$$anonfun$50.apply(Dataset.scala:3357)
	at org.apache.spark.sql.Dataset$$anonfun$54.apply(Dataset.scala:3492)
	at org.apache.spark.sql.Dataset$$anonfun$54.apply(Dataset.scala:3487)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:113)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:243)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:99)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:173)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withAction(Dataset.scala:3487)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3357)
	at sun.reflect.GeneratedMethodAccessor536.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$261: (string, string) => double)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$15$$anon$2.hasNext(WholeStageCodegenExec.scala:659)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1235)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:366)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:364)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1252)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:537)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:543)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Invalid text
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at org.apache.commons.text.similarity.RegexTokenizer.tokenize(RegexTokenizer.java:43)
	at org.apache.commons.text.similarity.RegexTokenizer.tokenize(RegexTokenizer.java:34)
	at org.apache.commons.text.similarity.CosineDistance.apply(CosineDistance.java:49)
	at uk.gov.moj.dash.linkage.CosineDistance.call(Similarity.scala:218)
	at uk.gov.moj.dash.linkage.CosineDistance.call(Similarity.scala:214)
	at org.apache.spark.sql.UDFRegistration$$anonfun$261.apply(UDFRegistration.scala:777)
	... 53 more

**Comment by Freewilly3d** [comment]
This appears to be a source column issue there was a column with 0 length that was not null.
