### ISSUE TITLE
`manually_apply_fellegi_sunter_weights` sometimes fails when using jaro winkler

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#187]
Error message is:

```
Caused by: org.apache.spark.SparkException: Failed to execute user defined function(UDFRegistration$$Lambda$902/1968746660: (string, string) => double)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.project_subExpr_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalArgumentException: CharSequences must not be null
```

This doesn't make any sense because if you run:
```
logging.getLogger("splink").setLevel(logging.DEBUG)
```

all `jaro_winkler` statements check for nulls before executing.

To make things more confusing `get_scored_comparisons`

The only difference is that `get_scored_comparisons` breaks lineage

This is on Spark 3.1.1.  Seems to work fine on Spark 3.0.1

So:

```
from utility_functions.demo_utils import get_spark
from splink.gammas import add_gammas 
from splink.blocking import block_using_rules
from splink.expectation_step import run_expectation_step

from splink.break_lineage import     default_break_lineage_blocked_comparisons
    
spark = get_spark() 
df = spark.read.parquet("data/fake_1000.parquet")


from splink import Splink
linker_db = Splink(settings_combined, df, spark)


## works
df_e_fn = linker_fn.get_scored_comparisons()

## Fails
df_e = linker_db.manually_apply_fellegi_sunter_weights()

from splink import Splink
linker_fn = Splink(settings_combined, df, spark)

## Works

df_comparison = block_using_rules(settings_combined, df, spark)
df_gammas = add_gammas(df_comparison, settings_combined, spark)
df_gammas = default_break_lineage_blocked_comparisons(df_gammas, spark)
df_e = run_expectation_step(df_gammas, linker_fn.model, spark)
    
    
df_e_fn = linker_fn.get_scored_comparisons()



df_e.show()
```

it can therefore be fixed by adding the break lineaage function to `manually_apply_fellegi_sunter_weights`. but it doesn't solve the issue of why it's happening.

The above sample code relates to `splink_demos`

**Comment by RobinL** [comment]
The only instance jaro is used is statements like this which should be immune to nulls:
```
  CASE
           WHEN surname_l IS NULL
                OR surname_r IS NULL THEN -1
           WHEN jaro_winkler_sim(surname_l, surname_r) >= 1.0 THEN 2
           WHEN jaro_winkler_sim(surname_l, surname_r) >= 0.88 THEN 1
           ELSE 0
       END AS gamma_surname,
```

**Comment by mamonu** [comment]
Just saw this...
One thing that I am thinking that needs to be sorted soon... 
(and that it needs to be taken care of even if its not the cause of this particular issue) :

For post spark 3.0+ version usage a jar to support them will be necessary to be compiled in scala 2.12

At this point the jar is compatible with spark 2.4+ as it has been compiled with Scala 2.11

However Spark 3.1.1 documentation for example says [here](https://spark.apache.org/docs/latest/building-spark.html#apache-maven) (and in many other places...)

`Spark requires Scala 2.12; support for Scala 2.11 was removed in Spark 3.0.0.`

Again perhaps not something for this exact moment. But as we move towards Spark 3.0 + versions we need to take care of it.

**Comment by mamonu** [comment]
Another quick fix would be to make sure from Scala that if either charsequence( =string)  is null to spit a default value (like the latlongexplode function)

btw the original Java code from Apache Commons library that we are using via Scala is [here](
https://commons.apache.org/proper/commons-text/jacoco/org.apache.commons.text.similarity/JaroWinklerDistance.java.html)  lines 68-88 .The exception is on 70-71

**Comment by RobinL** [comment]
It'll be interesting to see whether recompiling fixes this.    I never got to the bottom of why the error was occurring and why breaking lineage should fix it.  For the moment, not a big problem but I hate mysteries like that!

**Comment by RobinL** [comment]
Note:  We tested recomiling against the right Scala and it's still a problem so I now suspect this may be an issue with Spark 3.1.1
