### ISSUE TITLE
Java constructor does not exist

### ISSUE THREAD

**Issue by GodNooNoo** [moj-analytical-services/splink#1882]
### What happens?

When running spark example notebook "deduplicate_1k_synthetic" on a databricks 13.3 LTS ML cluster I get the following error.

```py
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
File <command-4474023138429393>, line 2
      1 from splink.spark.linker import SparkLinker
----> 2 linker = SparkLinker(df, settings, spark=spark)
      3 deterministic_rules = [
      4     "l.first_name = r.first_name and levenshtein(r.dob, l.dob) &lt;= 1",
      5     "l.surname = r.surname and levenshtein(r.dob, l.dob) &lt;= 1",
      6     "l.first_name = r.first_name and levenshtein(r.surname, l.surname) &lt;= 2",
      7     "l.email = r.email"
      8 ]
     10 linker.estimate_probability_two_random_records_match(deterministic_rules, recall=0.6)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9a4fece7-008c-46fb-b1d2-2f77ebd31d90/lib/python3.10/site-packages/splink/spark/linker.py:192, in SparkLinker.__init__(self, input_table_or_tables, settings_dict, break_lineage_method, set_up_basic_logging, input_table_aliases, spark, validate_settings, catalog, database, repartition_after_blocking, num_partitions_on_repartition, register_udfs_automatically)
    190 self.in_databricks = "DATABRICKS_RUNTIME_VERSION" in os.environ
    191 if self.in_databricks:
--> 192     enable_splink(spark)
    194 self._set_default_break_lineage_method()
    196 if register_udfs_automatically:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9a4fece7-008c-46fb-b1d2-2f77ebd31d90/lib/python3.10/site-packages/splink/databricks/enable_splink.py:27, in enable_splink(spark)
     24 converters = sc._jvm.scala.collection.JavaConverters
     26 JarURI = JavaURI.create("file:" + _jar_path)
---> 27 lib = JavaJarId(
     28     JarURI,
     29     ManagedLibraryId.defaultOrganization(),
     30     NoVersionModule.simpleString(),
     31 )
     32 libSeq = converters.asScalaBufferConverter((lib,)).asScala().toSeq()
     34 context = DatabricksILoop.getSharedDriverContextIfExists().get()

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1587, in JavaClass.__call__(self, *args)
   1581 command = proto.CONSTRUCTOR_COMMAND_NAME +\
   1582     self._command_header +\
   1583     args_command +\
   1584     proto.END_COMMAND_PART
   1586 answer = self._gateway_client.send_command(command)
-> 1587 return_value = get_return_value(
   1588     answer, self._gateway_client, None, self._fqn)
   1590 for temp_arg in temp_args:
   1591     if hasattr(temp_arg, "_detach"):

File /databricks/spark/python/pyspark/errors/exceptions/captured.py:188, in capture_sql_exception.<locals>.deco(*a, **kw)
    186 def deco(*a: Any, **kw: Any) -> Any:
    187     try:
--> 188         return f(*a, **kw)
    189     except Py4JJavaError as e:
    190         converted = convert_exception(e.java_exception)

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:330, in get_return_value(answer, gateway_client, target_id, name)
    326         raise Py4JJavaError(
    327             "An error occurred while calling {0}{1}{2}.\n".
    328             format(target_id, ".", name), value)
    329     else:
--> 330         raise Py4JError(
    331             "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332             format(target_id, ".", name, value))
    333 else:
    334     raise Py4JError(
    335         "An error occurred while calling {0}{1}{2}".
    336         format(target_id, ".", name))

Py4JError: An error occurred while calling None.com.databricks.libraries.JavaJarId. Trace:
py4j.Py4JException: Constructor com.databricks.libraries.JavaJarId([class java.net.URI, class java.lang.String, class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:203)
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:220)
	at py4j.Gateway.invoke(Gateway.java:255)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
```

### To Reproduce

Run the "deduplicate_1k_syntethic" notebook, or simply run
```py
%sh
pip install splink[spark]


from splink.databricks.enable_splink import enable_splink


enable_splink(spark) # This crashes
```

### OS:

Linux from DataBricks

### Splink version:

it says 3.9.11 I think, I am using splink[spark] should I not?

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
It's difficult for us to debug this sort of thing because we don't have databricks.  Do any of these suggestions help?
https://github.com/moj-analytical-services/splink/issues/1584#issuecomment-1718579809
https://github.com/moj-analytical-services/splink/issues/1734

**Comment by GodNooNoo** [comment]
downgrading to 11.3 worked indeed, thanks for the help 😄

**Comment by adelinor** [comment]
We are facing the same issue with Splink v3.9.2 and the Databricks runtime v13. We will downgrade to 11.3 and try again.
