### ISSUE TITLE
Docs build failing

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#2344]
see e.g. [here](https://github.com/moj-analytical-services/splink/actions/runs/10431724131)

Error message is:
`ModuleNotFoundError: No module named 'griffe.collections'`

Full message:

```
Run mkdocs build
  mkdocs build
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.19/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x64
    Python[2](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:3).9.19/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x6[4](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib
INFO    -  DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 90, in deprecation
    warnings.warn(message, DeprecationWarning, stacklevel=stacklevel + 1)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_client/connect.py", line 22, in 
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write

INFO    -  DeprecationWarning: [5](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:5).x style template file passed '/opt/hostedtoolcache/Python/3.9.19/x[6](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:6)4/lib/python3.9/site-packages/mknotebooks/templates/custom_markdown.tpl'. Use --template-name for the template directory with a index.<ext>.j2 file and/or --template-file to denote a different template.
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/traitlets/traitlets.py", line 1568, in _notify_observers
    c(event)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 240, in _template_file_changed
    warnings.warn(

INFO    -  DeprecationWarning: Passing unrecognized arguments to super(HTMLExporter).__init__(template_path=['/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mknotebooks/templates', '/home/runner/.local/share/jupyter/nbconvert/templates/base', '/opt/hostedtoolcache/Python/3.9.19/x64/share/jupyter/nbconvert/templates/base', '/usr/local/share/jupyter/nbconvert/templates/base', '/usr/share/jupyter/nbconvert/templates/base']).
object.__init__() takes exactly one argument (the instance to initialize)
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/traitlets/traitlets.py", line 1385, in __init__
    warn(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/traitlets/utils/warnings.py", line 14, in warn
    warnings.warn(msg, category=category, stacklevel=stacklevel, source=source)

INFO    -  [RSS-plugin]: 
                    Running on github actions might lead to wrong                     git revision dates due to a shallow git fetch depth.                     Try setting fetch-depth to 0 in your github action                     (see https://github.com/actions/checkout).
                    
INFO    -  [RSS-plugin]: 
                    Running on bitbucket pipelines might lead to wrong                     git revision dates due to a shallow git fetch depth.                     Try setting "clone: depth" to "full" in your pipeline                     (see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
                    and search 'depth').
                    
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/splink/splink/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
  - api_docs/column_expression.md
  - charts/template.ipynb
  - includes/tags.md
  - includes/generated_files/dataset_labels_table.md
  - includes/generated_files/datasets_table.md
WARNING -  A reference to 'topic_guides/comparisons/choosing_comparators.html#comparing-string-similarity-and-distance-scores' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING -  A reference to 'topic_guides/comparisons/choosing_comparators.html#choosing-thresholds' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING -  A reference to 'topic_guides/comparisons/choosing_comparators.html#phonetic-matching' is included in the 'nav' configuration, which is not found in the documentation files.
ERROR   -  Error reading page 'api_docs/blocking.md': No module named 'griffe.collections'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 115[7](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:7), in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 107[8](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:8), in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.[9](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:9).19/x64/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocs/__main__.py", line 284, in build_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocs/commands/build.py", line 3[10](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:10), in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocs/commands/build.py", line 167, in _populate_page
    page.render(config, files)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 285, in render
    self.content = md.convert(self.markdown)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/markdown/core.py", line 357, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/markdown/blockparser.py", line [11](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:12)7, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/markdown/blockparser.py", line 136, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/markdown/blockparser.py", line 158, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocstrings/extension.py", line [12](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:13)8, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocstrings/extension.py", line 199, in _process_block
    handler = self._handlers.get_handler(handler_name, handler_config)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocstrings/handlers/base.py", line 460, in get_handler
    module = importlib.import_module(f"mkdocstrings_handlers.{name}")
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocstrings_handlers/python/__init__.py", line 3, in <module>
    from mkdocstrings_handlers.python.handler import get_handler
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/mkdocstrings_handlers/python/handler.py", line [15](https://github.com/moj-analytical-services/splink/actions/runs/10431724131/job/28891698522#step:7:16), in <module>
    from griffe.collections import LinesCollection, ModulesCollection
ModuleNotFoundError: No module named 'griffe.collections'
Error: Process completed with exit code 1.
```

**Comment by RobinL** [comment]
The issue was that `griffe` recently (16th Aug) [released a new major version](https://pypi.org/project/griffe/1.0.0/)

I've now pinned

Here's a manual run showing this PR should fix:
https://github.com/moj-analytical-services/splink/actions/runs/10449426954
