### ISSUE TITLE
error with get_scored_comparisons()

### ISSUE THREAD

**Issue by ericmanning** [moj-analytical-services/splink#250]
Thank you for creating and publishing this package. I am familiar with R's fastLink, and hoping to use this in my own work as a faster solution.

I am attempting to implement your demo code on my institution's cluster and receiving the following error when calling `get_scored_comparisons()`

```
Traceback (most recent call last):
  File "/scratch/gpfs/ericmm/splink_demo/demo.py", line 30, in <module>
    df_e = linker.get_scored_comparisons()
  File "/home/ericmm/.local/lib/python3.8/site-packages/splink/__init__.py", line 101, in get_scored_comparisons
    df_comparison = block_using_rules(self.settings_dict, self.df, self.spark)
  File "/home/ericmm/.local/lib/python3.8/site-packages/typeguard/__init__.py", line 1032, in wrapper
    retval = func(*args, **kwargs)
  File "/home/ericmm/.local/lib/python3.8/site-packages/splink/blocking.py", line 204, in block_using_rules
    df.createOrReplaceTempView("df")
  File "/home/ericmm/.local/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 188, in createOrReplaceTempView
  File "/home/ericmm/.local/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1309, in __call__
  File "/home/ericmm/.local/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 117, in deco
pyspark.sql.utils.AnalysisException: Recursive view `df` detected (cycle: `df` -> `df`)
```

I am also getting the same error when implementing your demo code on my own machine. I am fairly unfamilar with Spark, so the issue may be my own. Just thought I'd flag. Any advice you can provide would be welcome. Thanks!

**Comment by RobinL** [comment]
Thanks for the report.  I haven't seen that error before. Are you able to post the full code you're running?  Also if you could let me know what version of spark you're using that'd be helpful

**Comment by ericmanning** [comment]
Once I rolled back to Spark 2.2 (rather than 2.4, which was temporarily unavailable on our cluster) I was unable to replicate the error. This is doubtless my fault, as I was using the wrong jar versions. I consider this closed. (Happy to discuss further if you'd find it helpful.)
