### ISSUE TITLE
2.4.7-amzn-1' is considered invalid by version checker

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#956]
When running splink on EMR cluster, the spark version value of '2.4.7-amzn-1' is considered invalid by version checker.  Any work around to this on the splink side?  If looks like the "-amzn-1" portion is what's causing failure, and I can't change what spark returns for version.

An error was encountered:
Invalid version: '2.4.7-amzn-1'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/splink/spark/spark_linker.py", line 154, in __init__
    if version.parse(self.spark.version) >= threshold and not self.catalog:
  File "/usr/local/lib/python3.7/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '2.4.7-amzn-1'

_Originally posted by @reygvasquez in https://github.com/moj-analytical-services/splink/discussions/954_

**Comment by RobinL** [comment]
A few notes:

The `packaging` module does not appear to be a builtin.  I get `ModuleNotFoundError: No module named 'packaging'` with a `ModuleNotFoundError: No module named 'packaging'`from `from packaging import version`

I don't think we have included it as a requirement or version controlled it (since i assumed it was a builtin).

I'm tempted to work with string comparisons (e.g. `"2.4.7-amzn-1" < "3.4.0"`), since this test should work in any plausible custom spark version

**Comment by RobinL** [comment]
Could us this as a backup https://stackoverflow.com/a/28568003/1779128
